### ISSUE TITLE
Items are not consumed after use

### ISSUE THREAD

**Issue by oniatus** [Terasology/Hunger#4]
Tested with latest cooking and hunger on [PR#3](https://github.com/Terasology/Hunger/pull/3):

- give yourself a consumable item, e.g. an AppliePie
- set your hunger to 10 (hungerSet 10 command)
- eat the pie
- the pie is not consumed.

By a short look, the `HungerAuthoritySystem` consumes the `ActivateEvent` and sends a `FoodConsumedEvent` instead. I found no usage of the `FoodConsumedEvent` though.
The `ItemAuthoritySystem` is responsible for removing consumable items on use but has a low event priority for `ActivateEvent` and never receives the event because it is consumed before.

Likely that this can be fixed easily by removing the `event.consume()` in the `HungerAuthoritySystem` but there may be a reason why we consume the event in the first place.

**Comment by Josharias** [comment]
@oniatus,  thank you for doing the investigation into this.  It looks like I did this pattern only half correctly when I implemented drinkable and fillable cups in JS.  The complexity that I needed to overcome, and why I mistakenly added the event consuming, was to allow only one interaction happen when activating a cup.  With a cup,  you could: drink the contents, dump the liquid into a tank, fill the cup from a water source, or fill the cup from a tank.  Without cancelling the event (with consume), all the actions could happen one after another, and depending on the order you could end up: filling the cup, drinking the cup, and emptying the cup all in the same ActivationEvent leaving you with the same empty cup that you started with.

Consuming the ActivateEvent currently means "cancel-and-stop-everything".  This is compared to some events in which consuming the event means, "handled-but-let-others-have-a-turn".  It would probably be helpful to make this distinction more clear for each event so that events are used correctly in all scenarios.

(thinking out loud) I suppose the solution to this could be one of:

1. Provide a different mechanism than consume to allow multiple systems to tell each other if an ActivationEvent has already been acted upon so that you could allow only one action per ActivationEvent.
2. Move the item destroying code someplace else that is not dependent on the ActivateEvent completing without being cancelled.

Any other thoughts?

**Comment by nihal111** [comment]
@Josharias I have used the second solution you suggested in the above referenced PR. Have a look. :)

**Comment by Cervator** [comment]
So interestingly this now works - for *Cooking* module items in multiplayer. Oddly the Joshaberry from JS still does not disappear. Both are fine in single player.

Also oddly the apple pie fails to improve the player's thirst level, it just works for the hunger level. 

In single player JS the Joshaberry is consumed but only fills up hunger, not thirst. In multiplayer JS *it fills thirst but not hunger* - that is mildly amusing in some bewildering fashion :D

Maybe something somewhere is consuming an event that had other stuff to do as well, and single vs. multi happens to be switching the order around or not triggering the first so only the second happens.

Maybe consuming a food item (or even drinking from a wooden cup) should re-trigger hunger and thirst specific events depending on which if any module is active, but not be consumed itself so any action can be attached?

Probably some of this works already. Mostly thinking out loud hoping it'll be useful.

Pinging @nihal111 and @xrtariq2594 for reference :-)
